hoodapp/urls.py
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'hoodapp'

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^homepage/$',views.homepage, name='homepage'),
    url(r'^profile/(?P<username>\w+)', views.profile, name='profile'),
    url(r'^user_profile/(?P<username>\w+)', views.user_profile, name='userprofile'),
    url(r'^update_profile/(?P<username>\w+)', views.update_profile, name='update'),
    url(r'signup/', views.signup, name='signup'),
    url(r'login/$',views.login_request, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'account/', include('django.contrib.auth.urls')),
    url(r'search/', views.search_business, name='search'),
    url(r'^post/', views.new_post, name='new_post'),
    url(r'^businesses/$',views.businesses, name='businesses'),
    url(r'^new_business/$',views.new_business, name='new_business'),
    url(r'^new_hood/$',views.create_neighbourhood, name='new_hood'),
    url(r'^all_hoods/',views.neighbourhoods, name='all_hoods'),
    url(r'^neighborhood/(\d+)',views.hood_details, name='onehood'),
    url(r'^security/$',views.security, name='security'),
    url(r'^health/$',views.health, name='health'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoodproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('hoodapp.urls')),
]

hoodapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

#Neighbourhood 
class Neighbourhood(models.Model):
    neighbourhood_name= models.CharField(max_length=100)
    location=models.CharField(max_length=30)
    population=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.neighborhood

    def create_neighbourhood(self):
        self.save()

    def delete_neighbourhood(self):
        self.delete()
    
    @classmethod
    def get_neighbourhoods(cls):
        estates = Neighbourhood.objects.all()
        return estates
    
    @classmethod
    def get_one_hood(cls,id):
        chosen_hood = cls.objects.get(id=id)
        return chosen_hood

#User Profile
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # user= models.ForeignKey(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='images/', default='default.png')
    name = models.CharField(blank=True, max_length=120)
    # neighbourhood = models.ForeignKey(neighbourhood,on_delete=models.CASCADE)
    location = models.CharField(max_length=60, blank=True)
    email = models.EmailField(max_length=100, blank=True)
    
    def __str__(self):
        return self.user
    
    @receiver(post_save, sender=User)
    def create_userprofile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_userprofile(sender, instance, **kwargs):
        instance.profile.save()

#Business
class Business(models.Model):
    image=models.ImageField(upload_to='business/', default = '/media/default.png')
    description = models.TextField(default='Tell Us More About Your Business')
    name=models.CharField(max_length=30,null=True)
    email=models.EmailField(max_length=70,blank=True)
    hood=models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.name
    
    def save_business(self):
        self.save()
    
    def delete_business(self):
        self.delete()
    
    @classmethod
    def search_business(cls, search_term):
        businesses = cls.objects.filter(name__icontains=search_term)
        return businesses
    
    @classmethod
    def find_business(cls,neighbourhood_id):
        messages = cls.objects.all().filter(hood=neighbourhood_id)
        return messages
    
#Post 
class Post(models.Model):
    title = models.CharField(max_length=155)
    image=models.ImageField(upload_to='photos/',null=True,blank=True)
    image_name=models.CharField(max_length=30)
    message=models.TextField(max_length=100,null=True,blank=True)
    estate=models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,null=True,blank=True)
    user_profile=models.ForeignKey(Profile)
    user=models.ForeignKey(User)

    def __str__(self):
        return f'{self.title}'

    def save_post(self):     
        self.save()

    def delete_post(self):     
        self.delete()

    @classmethod
    def get_posts(cls):      
        messages = cls.objects.all()
        return messages

#Security
class Security(models.Model):
    neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE)
    company = models.CharField(max_length=200)
    email = models.EmailField()
    contact = models.IntegerField()
    address =models.CharField(max_length=200)

    def __str__(self):
        return self.company

#Health
class Health(models.Model):
    # neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE)
    name =models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.IntegerField()
    address =models.CharField(max_length=100)
    hood=models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name

    def save_health(self):
        self.save()
    
    def delete_health(self):
        self.delete()

hoodapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Neighbourhood, Profile, Business, Post

#Neighbourhood
class NeighbourhoodForm(forms.ModelForm):
    class Meta:
        model = Neighbourhood
        fields = fields = ['neighbourhood_name','location', 'population']

#UpdateUser
class UpdateProfileForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email')

#Update User's Profile        
class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'location', 'profile_picture', 'email']
        exclude=['user'] 

#User Signup
class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=230)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

#Business
class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['image','name', 'email', 'description']
        exclude= ['hood', 'user']

#Post
class PostMessageForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','message']

hoodapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms import SignupForm, UpdateProfileForm, UpdateUserProfileForm, PostMessageForm, BusinessForm, NeighbourhoodForm
from .models import Neighbourhood, Profile, Business, Post, Security, Health

# Create your views here.
#Index Page
def index(request):
    return render(request, 'index.html')

#Homepage
@login_required(login_url='/accounts/login/')
def homepage(request):
    current_user =request.user
    hoods=Neighbourhood.get_neighbourhoods
    post=Post.objects.all()
    business=Business.find_business
    return render(request, 'homepage.html', {'user':current_user, "posts":post, "hoods":hoods, "business":business})


#User Signup
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('hoodapp:homepage')
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form })

#User Login
def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('hoodapp:homepage')
    else:
        form = AuthenticationForm()
    return render(request = request, template_name = "registration/login.html", context={"form":form})

#User Logout
def logout(request):
    auth.logout(request)
    return redirect('hoodapp:login')

#Profile
@login_required(login_url='/accounts/login/')
def profile(request, username):
    return render(request, 'profile.html')

#User Profile
def user_profile(request, username):
    user_prof = get_object_or_404(User, username=username)
    if request.user == user_prof:
        return redirect('profile', username=request.user.username)
    params = {
        'user_prof': user_prof,
    }
    return render(request, 'userprofile.html', params)

#Update User Profile
@login_required(login_url='/accounts/login/')
def update_profile(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        user_form = UpdateProfileForm(request.POST, instance=request.user)
        prof_form = UpdateUserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and prof_form.is_valid():
            user_form.save()
            prof_form.save()
            return redirect('hoodapp:profile', user.username)
    else:
        user_form = UpdateProfileForm(instance=request.user)
        prof_form = UpdateUserProfileForm(instance=request.user.profile)
    params = {
        'user_form': user_form,
        'prof_form': prof_form
    }
    return render(request, 'update.html', params)

#Display All Businesses
@login_required(login_url='/accounts/login/')
def businesses(request):
    current_user=request.user
    profile=Profile.objects.get(user=current_user)
    business_hood = profile.location
    businesses = Business.objects.filter(name=business_hood)

    return render(request,'all_businesses.html',{"businesses":businesses})

#Create New Business
@login_required(login_url='/accounts/login/')
def new_business(request):
    current_user=request.user
    profile =Profile.objects.get(user=current_user)

    if request.method=="POST":
        form =BusinessForm(request.POST,request.FILES)
        if form.is_valid():
            business = form.save(commit = False)
            business.user = current_user
            Neighbourhood.hood = profile.location
            business.save()

        return HttpResponseRedirect('/all_businesses')

    else:
        form = BusinessForm()

    return render(request,'new_business.html',{"form":form})

#Search Businesses
def search_business(request):
    if 'business' in request.GET and request.GET["business"]:
        search_term = request.GET.get("business")
        searched_businesses = Business.search_business(search_term)
        message = f"{search_term}"

        return render(request, 'search_results.html', {"message": message, "businesses": searched_business})

    else:
        message = "You have not searched for any business"
        return render(request, 'search_results.html', {"message": message})

#New Post
@login_required(login_url='/accounts/login/')
def new_post(request):
    current_user = request.user
    posts =Profile.objects.get(user = request.user.id)
    if request.method =='POST':
        form = PostMessageForm(request.POST,request.FILES)
        if form.is_valid():
            Post = form.save(commit=False)
            Post.user = current_user
            Post.user_profile = posts
            Post.save()
        return redirect('hoodapp:homepage')

    else:
        form = PostMessageForm()

    return render(request,'new_post.html',{"form":form})


#Create Neighbourhood
@login_required(login_url='/accounts/login')
def create_neighbourhood(request):
    # current_user = request.user
    # neighbourhood = Neighbourhood.objects.get(user = request.user.id)

    # if request.method=='post':
    #     form=NeighbourhoodForm(request.POST,request.files)
    #     if form.is_valid():
    #         neighbourhood=form.save(commit=False)
    #         neighbourhood.user=current_user
    #         neighbourhood.save()
    #         return redirect('homepage')

    #     else:
    #         form=NeighbourhoodForm()
    #     return render(request, 'neighbourhood.html',{"form":form})

    current_user = request.user   
    create_hood = Neighbourhood.create_neighbourhood
    return render(request, 'neighbourhood.html', {"user":current_user,"create_hood":create_hood})

#All Neighbourhoods
def neighbourhoods(request):
    current_user=request.user
    hoods=Neighbourhood.get_neighbourhoods
    return render (request,'allneighbourhoods.html',{"user":current_user,"hoods":hoods})

#One Neighbourhood
@login_required(login_url='/accounts/login')
def hood_details(request,neighbourhood_name):
    if len(Follow.objects.all().filter(user=request.user))>0:
        details=Neighbourhood.get_one_hood(neighbourhood_name)
        exists=Follow.objects.all().get(user=request.user)
    else:
        details=Neighbourhood.get_one_hood(neighbourhood_name)
        exists=0
    return render(request,'one_hood.html',{"exists":exists,"details":details})

#Security
@login_required(login_url='/accounts/login/')
def security(request):
    current_user=request.user
    profile=Profile.objects.get(user=current_user)
    security_details = profile.location
    security = Security.objects.filter(company=security_details)

    return render(request,'security.html',{"security":security})

#Health 
@login_required(login_url='/accounts/login/')
def health(request):
    current_user=request.user
    profile=Profile.objects.get(user=current_user)
    health_services = profile.location
    healthy = Health.objects.filter(name=health_services)
    return render(request,'health.html',{"healthy":healthy})

hoodapp/templates/allneighbourhoods.html
{% extends 'base.html' %} 
{% load static%}

{% block content %}

<div class="container">
        <div class="row">
        </div>
    
        <div class="row">
            {% for hood in hoods %}
            <div class="col-md-6">
                    <div class="card" style="width: 20rem;margin-top:10px;">
                      <div class="card-body">
                        <a href="{% url 'hoodapp:onehood' hood.id %}"><h3 class="card-title" data-toggle="modal">{{Neighbourhood.neighbourhood_name}}
                        </h3>
                      </div>
                    </div>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}

hoodapp/templates/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>

{% block content %}

<body>
    <div class="container-fluid" style="margin-top:5%;">
            <div class="container-fluid">
                    <!-- Businesses -->
                    <div class="col-md-4">
                            <a href="{% url 'hoodapp:businesses'%}">
                                <div class="panel panel-default" >
                                    <div class="panel heading;" style="height:50px;">
                                        <p>Businesses</p>
                                    </div>
                                    <div class="panel-body" style="height:300px;">
                                        
                                            <img class="card-img-top dark"
                                                src="/static/images/business.png"
                                                style="width:330px;height:250px;">
                                                <br>
                                                <br>
                                                <div class="text-center">
                                                        <a href="{% url 'hoodapp:new_business' %}">
                                                        <button class="btn btn-primary" style="height:50px;  margin-top: -6px;margin-left: -90px;">Register New Business</button>
                                                        </a>
                                                </div>
                                        </div>
                                    
                            </a>
                    
                    </div>
                    <br>
                    <br>

                    <!-- NeigbourHoods -->
                    <div class="col-md-4">
                            <a href="{% url 'hoodapp:all_hoods'%}">
                                <div class="panel panel-default" >
                                    <div class="panel heading;" style="height:50px;">
                                        <p>NeigbourHoods</p>
                                    </div>
                                    <div class="panel-body" style="height:300px;">
                                        
                                            <img class="card-img-top dark"
                                                src="/static/images/business.png"
                                                style="width:330px;height:250px;">
                                                <br>
                                                <br>
                                                <div class="text-center">
                                                        <a href="{% url 'hoodapp:new_hood' %}">
                                                        <button class="btn btn-primary" style="height:50px;  margin-top: -6px;margin-left: 50px;">Register New Neighbourhood</button>
                                                        </a>
                                                </div>
                                        </div>
                                    
                            </a>
                    </div>
                    <br>
                    <br>

                    <!-- Security -->
                    <div class="col-md-4">
                            <a href="{% url 'hoodapp:security'%}">
                                <div class="panel panel-default" >
                                    <div class="panel heading;" style="height:50px;">
                                        <p>Security</p>
                                    </div>
                                    <div class="panel-body" style="height:300px;">
                                        
                                            <img class="card-img-top dark"
                                                src="/static/images/business.png"
                                                style="width:330px;height:250px;">
                                                <br>
                                                <br>
                                                <div class="text-center">
                                                        <a href="{% url 'hoodapp:security' %}">
                                                        <button class="btn btn-primary" style="height:50px;  margin-top: -6px;margin-left: 50px;">View</button>
                                                        </a>
                                                </div>
                                        </div>
                                    
                            </a>
                    </div>
                    <br>
                    <br>

                    <!-- Health Services -->
                    <div class="col-md-4">
                            <a href="{% url 'hoodapp:health'%}">
                                <div class="panel panel-default" >
                                    <div class="panel heading;" style="height:50px;">
                                        <p>Health Services</p>
                                    </div>
                                    <div class="panel-body" style="height:300px;">
                                        
                                            <img class="card-img-top dark"
                                                src="/static/images/business.png"
                                                style="width:330px;height:250px;">
                                                <br>
                                                <br>
                                                <div class="text-center">
                                                        <a href="{% url 'hoodapp:health' %}">
                                                        <button class="btn btn-primary" style="height:50px;  margin-top: -6px;margin-left: 50px;">View</button>
                                                        </a>
                                                </div>
                                        </div>
                                    
                            </a>
                    </div>
                    <br>
                    <br>
                    <!-- Display Posts -->
                    <br>
                    <br>
                    <div class="container"> 
                        <section class="col-md-8 col-sm-12">
                            <h3 style="text-align:center;font-size: 28px">Posts</h3>
                            <br>
                            <a href="{% url 'hoodapp:new_post' %}">
                                    <button class="btn btn-primary" style="height:50px;  margin-top: -6px; margin-right: -30px ;">Create New Post</button>
                            </a>
                            <hr>
                            {%if posts %} 
                            {% for post in posts %}
                            <p>
                                Title: <span style="color:rgb(29, 26, 194); text-emphasis: bold;">{{post.title}}</span> 
                                    
                            </p>
                            <p>
                                <span style="color:rgb(5, 5, 54)"> {{post.user}}</span> {{post.message}}
                                
                            </p>

                            {% endfor %}
                                {% else %}
                            <p style="text-align:center">No Posts Available</p>
                            {% endif %}
                        </section>
                    </div>
            </div>
    </div>
{% endblock %}
</body>

                

hoodapp/templates/index.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>

<style>
    body {
    background: linear-gradient(253deg, #0cc898, #1797d2, #864fe1);
    background-size: 300% 300%;
    -webkit-animation: Background 25s ease infinite;
    -moz-animation: Background 25s ease infinite;
    animation: Background 25s ease infinite;
    }

    @-webkit-keyframes Background {
    0% {
      background-position: 0% 50%
    }
    50% {
      background-position: 100% 50%
    }
    100% {
      background-position: 0% 50%
    }
  }
  
  @-moz-keyframes Background {
    0% {
      background-position: 0% 50%
    }
    50% {
      background-position: 100% 50%
    }
    100% {
      background-position: 0% 50%
    }
  }
  
  @keyframes Background {
    0% {
      background-position: 0% 50%
    }
    50% {
      background-position: 100% 50%
    }
    100% {
      background-position: 0% 50%
    }
  }
  
  .full-screen {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background: url(https://i.imgur.com/wCG2csZ.png);
    background-size: cover;
    background-position: center;
    width: 100%;
    height: 100%;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    /* works with row or column */
    flex-direction: column;
    -webkit-align-items: center;
    align-items: center;
    -webkit-justify-content: center;
    justify-content: center;
    text-align: center;
  }
  
  h1 {
    color: #fff;
    font-family: 'Open Sans', sans-serif;
    font-weight: 800;
    font-size: 4em;
    letter-spacing: -2px;
    text-align: center;
    text-shadow: 1px 2px 1px rgba(0, 0, 0, .6);
  }
  
  h1:after {
    display: block;
    color: black;
    letter-spacing: 1px;
    font-family: 'Poiret One', sans-serif;
    content: 'Your NeighbourHood Watch App';
    font-size: .4em;
    text-align: center;
  }
  
  .button-line {
    font-family: 'Open Sans', sans-serif;
    text-transform: uppercase;
    letter-spacing: 2px;
    background: transparent;
    border: 1px solid #fff;
    color: #fff;
    text-align: center;
    font-size: 1.4em;
    opacity: .8;
    padding: 20px 40px;
    text-decoration: none;
    transition: all .5s ease;
    margin: 0 auto;
    display: block;
    width: 100px;
  }
  
  .button-line:hover {
    opacity: 1;
  }
</style>

<body>
    <div class="full-screen">
        <div>
            <h1>Hood Eye 👁</h1>
            <br>
            <a class="button-line" href="{% url 'hoodapp:login' %}">Log In</a> 
            <br>
            <a class="button-line" href="{% url 'hoodapp:signup' %}">Sign Up</a> 
        </div>
    </div>
</body>

<!-- <footer>
    <h4>Hood Eye</h4>
    <h3 class="button">Download on Google Play</h3>
    <div id="links"><div><h4>About</h4>
    <ul>
        <li>Company</li>
        <li>Company</li>
        <li>Company</li>
        </ul></div>  

    <div><h4>Legal</h4>
    <ul>
        <li>Company</li>
        <li>Company</li>
        <li>Company</li>
        </ul></div>
    <div><h4>Support</h4>
    <ul>
        <li>Company</li>
        <li>Company</li>    
        </ul></div>
    <div><h4>Social</h4>
    <ul>
        <li>Company</li>
        <li>Company</li>
        <li>Company</li>
        </ul></div></div>
    <p>Hood Eye by ExistentialCrisis © All right reserved 2020.</p>
</footer> -->

hoodapp/templates/navbar.html
{% load crispy_forms_tags %}

<nav id="scanfcode" class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" id="toogle-button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
       <span class="glyphicon glyphicon-menu-hamburger"></span>                     
      </button>
      <a id="logo" class="navbar-brand" href="{% url 'hoodapp:homepage' %}">Hood Eye 👁</a>
    </div>

    <div>
 
        <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <form class="form-inline" method="GET" action="{% url 'hoodapp:search' %}">
                        {% csrf_token %}
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2 " type="text" placeholder="Search" name="title" aria-label="Search">
                        </div>
                    </form>
                </li>
        </ul>

        <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated%}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">{{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item text-center" href="{% url 'hoodapp:profile' user.username %}">Profile</a>
                        <a class="dropdown-item text-center" href="{% url 'hoodapp:update' user.username  %}"> Update Profile</a>
                        <hr>
                        <hr>
                        <a href="{% url 'hoodapp:logout' %}" class="text-secondary text-center dropdown-item">Log Out</a>
                    </div>
                </li>
                {% endif %}
        </ul>

        <!-- <ul id="link" class="nav navbar-nav navbar-right">
            <li class="dropdown" id="first-link">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">More <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
        </ul>
            </li> -->

        <ul id="link" class="nav navbar-nav navbar-right">  
        <li><a href="{% url 'hoodapp:login' %}">Log In</a></li>
        <li id="button-link"><a href="{% url 'hoodapp:signup' %}">Sign Up</a></li>
        </ul>
    </div>
  </div>
</nav>

hoodapp/templates/new_business.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container" style="margin-top:7%;">
    <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-9">

                <div class="card" style="margin-top:2%; padding:20px">
                    <div class="card-body">
                        <h5 class="card-title">New Business</h5>
                        <div class="card-text">
                            <form action="{% url 'hoodapp:businesses' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy}}
                                <button type="submit" class="btn btn-info btn-sm"> Create </button>
                            </form>
                        </div>
                    </div>
                </div>
    
            </div>
            <div class="col-md-1"></div>
        </div>
</div>
{% endblock %}

hoodapp/templates/new_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container" style="margin-top:8%; margin-left:5px; ">
    <!-- <h5 class="mb-4 mt-4">{{ post.title }} by {{ post.user.username }} from {{ post.user.profile.location }} <span
        id="heart"> <i class="fas fa-heart"></i></span></h5> -->
    <h5 >Create Your Post</h5>
</div>

<div class="panel panel-default">
        <div class="panel-body">
          <form action="{% url 'hoodapp:new_post'%}" method="post"  enctype="multipart/form-data">
    
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group text-center">
              <input type="submit" class="btn btn-primary sign-up-button" value="Post">
            </div>
            <input type="hidden" name="next" value="{{next}}">
          </form>
        </div>
 </div>

{% endblock %} 